object Dependencies {
    const val gradlePluginVersion = "7.4.2"
    const val kotlinPluginVersion = "1.8.10"
    const val kotlinVersion = "1.8.10"
    const val daggerHiltVersion = "2.43.2"
    const val detektPluginVersion = "1.15.0"

    const val junitVersion = "4.13.2"
    const val androidxJunitVersion = "1.1.3"
    const val espressoVersion = "3.5.0"

    const val coreKtxVersion = "1.9.0"
    const val constraintLayoutVersion = "2.1.4"
    const val recyclerviewVersion = "1.2.1"
    const val materialVersion = "1.4.0"
    const val lifecycleVersion = "2.5.0"

    const val retrofitVersion = "2.9.0"
    const val okhttpVersion = "4.9.1"
    const val roomVersion = "2.3.0"
    const val moxyVersion = "2.2.2"
    const val coroutineVersion = "1.6.4"
    const val viewBindingPropertyDelegateVersion = "1.5.6"
    const val rxBindingVersion = "2.2.0"
    const val lottieAnimationVersion = "5.2.0"
    const val sdpAndroidVersion = "1.0.6"
    const val ciceroneVersion = "6.6"
    const val lifecycleVersion = "2.3.1"
    const val lifecycleExtensionsVersion = "2.2.0"
}
